version: '3.8'

services:
  postgres:
    container_name: postgres_db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=marchMadness
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d marchMadness"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mosquitto

  # PostgreSQL pgAdmin panel accessible at http://localhost:16543/
  pgadmin-compose:
    container_name: pgadmin_service
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "brandon@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "all4Postgres!"
      PGPASSWORD: root
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - mosquitto

  mqtt_server:
    container_name: mqtt_server
    image: eclipse-mosquitto
    ports:
     - 1883:1883
     - 9001:9001
     - 8083:8083
     - 8883:8883
    volumes:
      - ./docker/mqtt/config:/mosquitto/config:rw
      - ./docker/mqtt/data:/mosquitto/data:rw
      - ./docker/mqtt/log:/mosquitto/log:rw
      - ./scripts:/scripts
    restart: always
    networks:
      - mosquitto

volumes:
  config:
  data:
  log:
  logs:

networks:
  mosquitto:
    driver: bridge